import Foundation

vocabularyRulesTests()
textCleanerTests()
commandProcessorTests()
speechSegmenterTests()
transcriptDiffTests()
casingCommandsTests()
transcriptAccuracyTests()
symbolCommandsTests()
languageSmoothingTests()
numberWordsTests()
snippetTests()
correctionDetectorTests()
contextBoostTests()
exit(summary())
